#!/usr/bin/env python
import shutil
import subprocess

shutil.copy('talk.tex', 'build/talk.tex')
shutil.copy('fork-tag.py', 'build/fork-tag.py')
subprocess.check_call(['pdflatex', 'talk.tex'], cwd='build')
