#!/usr/bin/env python
import datetime
import subprocess

NOW = datetime.datetime.now()
TAG = NOW.isoformat().replace(':', '-').replace('.', '-')

subprocess.check_call(['docker', 'pull', 'pypy:3-slim'])
subprocess.check_call(['docker', 'tag', 'pypy:3-slim',
                                        'moshez/pypy3:' + TAG])
subprocess.check_call(['docker', 'push', 'moshez/pypy3:' + TAG])
